# --- td3 specific parameters ---
action_range: ~
action_selector: ~
agent: mlp
obs_agent_id: False
obs_last_action: False
agent_output_type: ~
batch_size_run: 1
batch_size: 100
buffer_size: 1000000
buffer_warmup: 1000     ###
discretize_actions: False
double_q: True
epsilon_decay_mode: ~
epsilon_start: ~
epsilon_finish: ~
epsilon_anneal_time: ~
exploration_mode: "gaussian"   ####

start_steps: 10000 # Number of steps for uniform-random action selection, before running real policy. Helps exploration.
act_noise: 0.1 # Stddev for Gaussian exploration noise added to policy at training time.
ou_theta: 0.15 # D
ou_sigma: 0.2 # D
ou_noise_scale: 0.3
final_ou_noise_scale: 0.
gamma: 0.99
grad_norm_clip: 0.5
learner: "td3_learner"
learn_interval: 2  # ##==licy_freq ？
lr: 0.001
critic_lr: 0.001
td_lambda: 0.8
critic_train_reps: 1  ##nr_of_steps=
q_nstep: 1  # 0 corresponds to default Q, 1 is r + gamma*Q, etc
mac: cqmix_mac
name: "td3_mamujoco_wei"
n_runners: ~
n_train: 1
nr_of_steps: 2
optimizer: adam # D
optimizer_epsilon: 0.01 # D
ou_stop_episode: 100 # training noise goes to zero after this episode
rnn_hidden_dim: 400
run_mode: ~
runner: "parallel"
runner_scope: 'transition'
target_update_interval: ~
recurrent_critic: False
target_update_mode: "soft"
target_update_tau: 0.001
test_greedy: ~
test_interval: 4000
test_nepisode: 10
testing_on: True
t_max: 2000000
save_model: Fe
save_model_interval: 10000
verbose: False
weight_decay: True
weight_decay_factor: 0.0001
env_args:
  state_last_action: False # critic adds last action internally
agent_return_logits: False
q_embed_dim: 2
